# Generated by Django 3.2.4 on 2021-06-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('engine', models.CharField(max_length=50, verbose_name='Двигатель')),
                ('speed', models.CharField(max_length=50, verbose_name='Разгон(0-100)')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
